import React from "react";
import { Info, AlertCircle, FileText, Sparkles, Target, Settings, ArrowRight, BrainCircuit, Activity, CheckCircle2 } from "lucide-react";
import { SimulationPhase } from "../hooks/useInvestigationSimulation";

interface InvestigationNarrativeProps {
  investigation: any;
  assessment?: any;
  capa: any;
  evidenceItems: any[];
  simulation?: any;
  onOpenCapaEditor?: () => void;
  onCitationClick?: (citation: any) => void;
}

export const InvestigationNarrative: React.FC<InvestigationNarrativeProps> = ({ 
  investigation, 
  assessment, 
  capa,
  evidenceItems,
  simulation,
  onOpenCapaEditor,
  onCitationClick
}) => {
  const phase: SimulationPhase = simulation?.phase || 'IDLE';

  if (phase !== 'READY' || !assessment) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-12 bg-white/5 border border-white/10 rounded-2xl backdrop-blur-md shadow-xl">
        <Sparkles size={48} className="text-slate-600 mb-6 opacity-50" />
        <h3 className="text-xl font-bold text-slate-400 mb-2">Investigation Assessment</h3>
        <p className="text-slate-500 text-center max-w-sm">
          Run the Intelligence Layer to generate the evidence-backed investigation assessment.
        </p>
      </div>
    );
  }

  // Confidence Color Logic
  const confidenceScore = assessment.confidence?.score || 0;
  let confidenceColor = "text-emerald-400";
  let confidenceBg = "bg-emerald-500/10";
  let confidenceBorder = "border-emerald-500/20";
  let confidenceLabel = "HIGH";
  
  if (confidenceScore < 70) {
    confidenceColor = "text-rose-400";
    confidenceBg = "bg-rose-500/10";
    confidenceBorder = "border-rose-500/20";
    confidenceLabel = "LOW";
  } else if (confidenceScore < 85) {
    confidenceColor = "text-amber-400";
    confidenceBg = "bg-amber-500/10";
    confidenceBorder = "border-amber-500/20";
    confidenceLabel = "MEDIUM";
  }

  return (
    <div className="bg-white/5 border border-white/10 rounded-2xl p-8 backdrop-blur-md shadow-xl h-full overflow-y-auto custom-scrollbar">
      
      {/* Header */}
      <div className="flex items-center justify-between border-b-2 border-white/10 pb-6 mb-8">
        <div>
          <h2 className="text-2xl font-black text-slate-100 tracking-tight uppercase">Investigation Assessment</h2>
          <p className="text-sm font-medium text-slate-400 mt-1">Generated by EvidenceOps Intelligence Layer</p>
        </div>
        
        {/* Premium Confidence Badge */}
        <div className={`flex flex-col items-end px-4 py-2 rounded-xl border ${confidenceBg} ${confidenceBorder}`}>
           <span className={`text-[10px] font-black uppercase tracking-widest ${confidenceColor}`}>{confidenceLabel} CONFIDENCE</span>
           <span className={`text-2xl font-black ${confidenceColor}`}>{confidenceScore}%</span>
        </div>
      </div>

      <div className="space-y-12">
        
        {/* ROOT CAUSE */}
        <section>
          <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
            <BrainCircuit size={16} className="text-violet-400" />
            Root Cause Summary
          </h3>
          <p className="text-base text-slate-200 leading-relaxed whitespace-pre-line font-medium pl-6 border-l-2 border-violet-500/30">
            {assessment.summary}
          </p>
        </section>

        {/* EVIDENCE CITATIONS */}
        {assessment.evidence && assessment.evidence.length > 0 && (
          <section>
            <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
              <FileText size={16} className="text-blue-400" />
              Supporting Evidence
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pl-6">
              {assessment.evidence.map((ev: any, i: number) => (
                <button 
                  key={i}
                  onClick={() => onCitationClick && onCitationClick(ev)}
                  className="flex items-start gap-3 p-3 rounded-xl bg-slate-900/50 border border-white/5 hover:border-blue-500/30 hover:bg-blue-500/5 transition-all text-left"
                >
                  <CheckCircle2 size={16} className="text-blue-400 shrink-0 mt-0.5" />
                  <div>
                    <span className="block text-sm font-bold text-slate-200 truncate">{ev.source}</span>
                    <span className="block text-xs text-slate-500 truncate mt-0.5">{ev.document_id || "Source Document"}</span>
                  </div>
                </button>
              ))}
            </div>
          </section>
        )}

        {/* MISSING INFORMATION */}
        {assessment.missing_evidence && assessment.missing_evidence.length > 0 && (
          <section>
            <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
              <AlertCircle size={16} className="text-amber-400" />
              Missing Information
            </h3>
            <div className="pl-6 space-y-3">
              {assessment.missing_evidence.map((me: any, i: number) => (
                <div key={i} className="flex items-start gap-3 p-4 rounded-xl bg-amber-500/5 border border-amber-500/10">
                  <AlertCircle size={16} className="text-amber-400 shrink-0 mt-0.5" />
                  <div>
                    <span className="block text-sm font-bold text-amber-200/90">{me.description}</span>
                    <span className="block text-xs text-amber-500/70 mt-1 uppercase tracking-wider font-semibold">Priority: {me.priority}</span>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* RECOMMENDATIONS & NEXT ACTIONS */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 border-t-2 border-white/10 pt-8">
          
          <section>
            <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
              <Target size={16} className="text-emerald-400" />
              Recommendations
            </h3>
            <ul className="space-y-3 pl-2">
              {assessment.recommendations?.map((rec: string, i: number) => (
                <li key={i} className="flex items-start gap-3 text-sm text-slate-300">
                  <span className="text-emerald-500 font-bold mt-0.5">•</span>
                  <span className="leading-relaxed">{rec}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
              <Activity size={16} className="text-blue-400" />
              Next Actions
            </h3>
            <ul className="space-y-3 pl-2">
              {assessment.next_actions?.map((act: string, i: number) => (
                <li key={i} className="flex items-start gap-3 text-sm text-slate-300">
                  <span className="text-blue-500 font-bold mt-0.5">•</span>
                  <span className="leading-relaxed">{act}</span>
                </li>
              ))}
            </ul>
            
            {/* CAPA CTA */}
            <div className="mt-6 pt-6 border-t border-white/5">
              {!capa ? (
                <button
                  onClick={onOpenCapaEditor}
                  className="w-full flex items-center justify-center gap-2 text-sm font-bold text-emerald-400 hover:text-emerald-300 bg-emerald-500/10 px-4 py-3 rounded-xl border border-emerald-500/20 hover:border-emerald-400/40 transition-all shadow-ai"
                >
                  Draft CAPA Plan with AI
                  <ArrowRight size={16} />
                </button>
              ) : (
                <button
                  onClick={onOpenCapaEditor}
                  className="w-full flex items-center justify-center gap-2 text-sm font-bold text-emerald-400 hover:text-emerald-300 bg-emerald-500/10 px-4 py-3 rounded-xl border border-emerald-500/20 hover:border-emerald-400/40 transition-all"
                >
                  Review Approved CAPA
                  <ArrowRight size={16} />
                </button>
              )}
            </div>
          </section>

        </div>

      </div>
    </div>
  );
};
